version: "3"
services:
  authn:
    build: 
      context: src/services/authn
      target: dev
    tty: true
    volumes:
      - ./src/services/authn:/app
      - ./src/shared:/app/shared
    ports:
      - 8000:8000
    environment:
      REDIS_IP: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: user
  authz:
    build: 
      context: src/services/authz
      target: dev
    tty: true
    volumes:
      - ./src/services/authz:/go/src/authz
      - ./src/shared:/go/src/authz/
    ports:
      - 8006:8000
  gateway:
    build: 
      context: src/services/gateway
      target: dev
    tty: true
    volumes:
      - ./src/services/gateway:/go/src/gateway
      - ./src/shared:/go/src/gateway/shared
    ports:
      - 8002:8000
    environment:
      REDIS_IP: redis
      REDIS_PORT: "6379"
      REDIS_PASSWORD: user

  pveapi:
    build: 
      context: src/services/pveapi
      target: dev
    tty: true
    volumes:
      - ./src/services/pveapi:/go/src/pveapi
      - ./src/shared:/go/src/pveapi/shared
      - ~/.ssh/id_ed25519:/ssh/id_ed25519
    ports:
      - 8001:8000
    environment:
      PROXMOX_API_URL: https://10.1.10.30:8006/api2/json
      PROXMOX_API_TOKEN: ctf_dev@pam!ctf_dev=f35db674-1d85-4f99-b8dc-1e9cecadaeea
      CLOUDINIT_FILESERVER_IP: 10.1.10.30
  contest:
    build: 
      context: src/services/contest
      target: dev
    tty: true
    volumes:
      - ./src/services/contest:/go/src/contest
      - ./src/shared:/go/src/contest/shared
    ports:
      - 8003:8000
  team:
    build: 
      context: src/services/team      
      target: dev
    tty: true
    volumes:
      - ./src/services/team:/go/src/team
      - ./src/shared:/go/src/team/shared
    ports:
      - 8004:8000
  question:
    build: 
      context: src/services/question
      target: dev
    tty: true
    volumes:
      - ./src/services/question:/go/src/question
      - ./src/shared:/go/src/question/shared
    ports:
      - 8005:8000

  db:
    image: mysql:8.0
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/logs:/var/log/mysql
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mysql/sample.sql:/docker-entrypoint-initdb.d/sample.sql
      - ./mysql/product.sql:/docker-entrypoint-initdb.d/product.sql
    environment:
      - MYSQL_DATABASE=ctf
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
      - MYSQL_ROOT_PASSWORD=root
      - TZ=Asia/Tokyo
    ports:
      - 3306:3306
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - "./redis/data:/data"
      - "./redis/redis.conf:/usr/local/etc/redis/redis.conf"
  # nfs:
  #   build: 
  #     context: nfs
  #   privileged: true
  #   ports:
  #     - "2049:2049"    # NFS データポート
  #     - "20048:20048"  # NFS マウントポート    
  #   volumes:
  #     - nfs-data:/share
  #     - "./nfs/exports:/etc/exports"
  #   tty: true
  traefik:
    image: traefik:v3.2
    ports:
        # The HTTP port
        - "80:80"
        # The Web UI (enabled by --api.insecure=true)
        - "8080:8080"
    command: --api.insecure=true --providers.docker
    volumes:
      - ./traefik:/etc/traefik/
      - ./logs:/var/log/traefik  # ログファイルをマウント
  # whoami:
  #   # A container that exposes an API to show its IP address
  #   image: traefik/whoami
  #   labels:
  #     - "traefik.http.routers.whoami.rule=Host(`whoami.docker.localhost`)"
volumes:
  nfs-data:
    name: "nfs-data"